name: 'Build AUR Package'
branding:
  icon: user-check
  color: gray-dark
inputs:
  repo-name:
    description: 'AUR repository name to build'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo-name }}
